### ISSUE TITLE
Is wk_time 1.7 compatible with Redmine 3.0.1?

### ISSUE THREAD

**Issue by hpduy17** [dhanasingh/redmine_wktime#10]
I have upgraded my Redmine to version 3.0.1 , I have installed wk_time 1.7 but when I login by my account I meet an 500 Internal Server Error. Although I haved run all needed command ( rake ,bundle ,...) and my redmine run fine after I remove this plugin out of my plugins directory. So Is wk_time compatible with redmine 3.0.1?
This is my production.log
```
Processing by WelcomeController#index as HTML
  Current user: hpduy17 (id=41)
  Rendered welcome/index.html.erb within layouts/base (7.9ms)
Completed 200 OK in 52ms (Views: 23.5ms | ActiveRecord: 8.5ms)
Processing by WelcomeController#index as HTML
  Current user: hpduy17 (id=41)
  Rendered welcome/index.html.erb within layouts/base (201.7ms)
Completed 500 Internal Server Error in 729ms

ActiveRecord::RecordNotFound (Couldn't find all Projects with 'id': (all, {:conditions=>"((projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='time_tracking')) AND (projects.id IN (14,5,16)))"}) (found 0 results, but was looking for 2)):
  app/models/project.rb:296:in `find'
  lib/redmine/menu_manager.rb:446:in `call'
  lib/redmine/menu_manager.rb:446:in `allowed?'
  lib/redmine/menu_manager.rb:164:in `block in menu_items_for'
  lib/redmine/menu_manager.rb:163:in `each'
  lib/redmine/menu_manager.rb:163:in `menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
```

**Comment by dhanasingh** [comment]
Correct, time & expense 1.7 is not compatible with redmine 3.0.1

**Comment by dhanasingh** [comment]
Time & Expense 1.8 is compatible with redmine 3.0.1
