### ISSUE TITLE
Redmine 404 on ERPMine report & 500 on ERPMine configuration on v2.8

### ISSUE THREAD

**Issue by davidbouche** [dhanasingh/redmine_wktime#102]
Hello,

Here's my configuration

```
Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.16
  Git                            2.12.2
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.2
  redmine_contacts               4.0.6
  redmine_contacts_helpdesk      3.0.7
  redmine_wktime                 2.8
```

Here's the log error : 

```
Started GET "/wkreport/index" for 62.210.92.244 at 2017-06-01 15:47:22 +0000
Processing by WkreportController#index as HTML
 Current user: dbouche (id=177)
 Rendered plugins/redmine_wktime/app/views/wkreport/index.html.erb within layouts/base (1.1ms)
Missing template, responding with 404
 Rendered common/error.html.erb within layouts/base (0.1ms)
 Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (1.2ms)
Completed 404 Not Found in 8541ms (Views: 47.7ms | ActiveRecord: 8464.5ms)
.../...
Started GET "/wkcrmenumeration/index" for 62.210.92.244 at 2017-06-01 15:47:55 +0000
Processing by WkcrmenumerationController#index as HTML
 Current user: dbouche (id=177)
Completed 500 Internal Server Error in 227ms (ActiveRecord: 221.3ms)
 plugins/redmine_wktime/app/controllers/wkcrmenumeration_controller.rb:65:in `formPagination'
ActiveRecord::StatementInvalid (Mysql2::Error: Table 'bow7owedk.wk_crm_enumerations' doesn't exist: SHOW FULL FIELDS FROM `wk_crm_enumerations`):
 lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 plugins/redmine_wktime/app/controllers/wkcrmenumeration_controller.rb:22:in `index'
```

Theses issues appear after upgrade 2.8.

Thanks for your support,
David

**Comment by karthickmadhiazhagan** [comment]
Hi, 
  From what version of ERPmine you trying to upgrade to 2.8?
Are you running plugin migration as given in the [installation notes](http://www.redmine.org/plugins/wk-time) ?

Thanks,
Karthick

**Comment by davidbouche** [comment]
I'm upgrading from 2.7.
I've just lauched rake redmine:plugins:migrate (normaly it updates all plugins, no ?)

Thanks for your support.
David.

**Comment by dhanasingh** [comment]
you can run it for a single plugin also by mentioning the name of the plugin

    rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
