### ISSUE TITLE
TypeError (nil can't be coerced into Float)

### ISSUE THREAD

**Issue by ser-j** [dhanasingh/redmine_wktime#111]
After some changes in the UI I start getting 500 error on the below mentioned page.

```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.9.1
```

```
Started GET "/wkpayroll/index?tab=payroll" for 192.168.1.107 at 2017-09-01 20:52:47 +0300
Processing by WkpayrollController#index as HTML
  Parameters: {"tab"=>"payroll"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 61ms (ActiveRecord: 49.3ms)
TypeError (nil can't be coerced into Float):
  plugins/redmine_wktime/app/controllers/wkpayroll_controller.rb:77:in `+'
  plugins/redmine_wktime/app/controllers/wkpayroll_controller.rb:77:in `block in index'
  plugins/redmine_wktime/app/controllers/wkpayroll_controller.rb:77:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by dhanasingh** [comment]
what changes did you make ?
did you try the latest version of erpmine ?
