### ISSUE TITLE
ActionView::Template::Error (undefined method `<<' for nil:NilClass)

### ISSUE THREAD

**Issue by ser-j** [dhanasingh/redmine_wktime#113]
I have reinstalled plugin and migration.  I had this error after clean initial install as well and it persisted again without doing even any modifications. 
```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.9.1
```
```
Started GET "/wkpayroll/user_salary_settings?tab=usersettings&user_id=1" for 192.168.1.107 at 2017-09-01 22:01:31 +0300
Processing by WkpayrollController#user_salary_settings as HTML
  Parameters: {"tab"=>"usersettings", "user_id"=>"1"}
  Current user: admin (id=1)
  Rendered plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb within layouts/base (2.3ms)
Completed 500 Internal Server Error in 72ms (ActiveRecord: 62.3ms)

ActionView::Template::Error (undefined method `<<' for nil:NilClass):
    28:                         factor = entry.sc_factor.blank? ? 0 : ("%.2f" % entry.sc_factor)
    29:                 end
    30:                 actualSalValHash[entry.sc_component_type].store entry.sc_id, @userSalHash[entry.user_id][entry.sc_id] unless @userSalHash[entry.user_id].blank?
    31:                 salEntryByTypeHash[entry.sc_component_type] = salEntryByTypeHash[entry.sc_component_type] << [entry, isOverride, dependent_id, factor]
    32:         end
    33:         %>
    34:
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:31:in `block (2 levels) in _plugins_redmine_wktime_app_views_wkpayroll_user_salary_settings_html_erb___2030938898178524059_70194275844160'
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:21:in `each'
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:21:in `block in _plugins_redmine_wktime_app_views_wkpayroll_user_salary_settings_html_erb___2030938898178524059_70194275844160'
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:1:in `_plugins_redmine_wktime_app_views_wkpayroll_user_salary_settings_html_erb___2030938898178524059_70194275844160'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by ser-j** [comment]
Also, note that I first upgraded Redmine from 2.4 to the latest stable release and then installed your WKtime.

**Comment by Nevyn75** [comment]
Hi.
Same problem here trying to set payroll for users:

```
  Rendered plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb within layouts/base (5.0ms)
Completed 500 Internal Server Error in 70ms (ActiveRecord: 53.9ms)

ActionView::Template::Error (undefined method `<<' for nil:NilClass):
    28:                         factor = entry.sc_factor.blank? ? 0 : ("%.2f" % entry.sc_factor)
    29:                 end
    30:                 actualSalValHash[entry.sc_component_type].store entry.sc_id, @userSalHash[entry.user_id][entry.sc_id] unless @userSalHash[entry.user_id].blank?
    31:                 salEntryByTypeHash[entry.sc_component_type] = salEntryByTypeHash[entry.sc_component_type] << [entry, isOverride, dependent_id, factor]
    32:         end
    33:         %>
    34:
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:31:in `block (2 levels) in _plugins_redmine_wktime_app_views_wkpayroll_user_salary_settings_html_erb__4273310167557225898_47189234396060'
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:21:in `each'
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:21:in `block in _plugins_redmine_wktime_app_views_wkpayroll_user_salary_settings_html_erb__4273310167557225898_47189234396060'
  plugins/redmine_wktime/app/views/wkpayroll/user_salary_settings.html.erb:1:in `_plugins_redmine_wktime_app_views_wkpayroll_user_salary_settings_html_erb__4273310167557225898_47189234396060'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Thx.

**Comment by dhanasingh** [comment]
can you give us the version details of redmine, erpmine, OS, Database etc ?

**Comment by dhanasingh** [comment]
have you setup the Basic Pay, Allowances and Deductions under
Administration -> plugins -> ERPmine -> Payroll

May be it is throwing a null pointer error, since they are empty, can you fill them up

**Comment by Nevyn75** [comment]
Oh yes.
Thank you very much! I forgot to set those values. Now the page opens with no crash.

Do you mind if I ask you another small help?

I receive a 403 "You are not authorized to access this page." error if I try to enter on Tax Setting tab, but I'm not able to find out where this permission should be set.

Thank you and best regards.

**Comment by dhanasingh** [comment]
Glad the payroll setting page issue is resolved.
for the tax settings, you will have to be in the billing admin group.
Tas is part of the billing module
To set the billing admin group.
Administration -> plugins -> ERPmine -> Billing
choose the billing admin group and you will have to part of that group.

**Comment by Nevyn75** [comment]
Thx again, also this resolved.

Very good job with this plugin: complete and useful.

Best regards.

**Comment by dhanasingh** [comment]
glad the issue with the tax tab is resolved.
When you get a chance please rate our plugin here http://www.redmine.org/plugins/wk-time
