### ISSUE TITLE
undefined method `format_hours'

### ISSUE THREAD

**Issue by L0rD59** [dhanasingh/redmine_wktime#131]
Hi,

I've Internal Server Error with v3.1 version : 

```
Completed 500 Internal Server Error in 316ms (ActiveRecord: 54.1ms)

ActionView::Template::Error (undefined method `format_hours' for #<#<Class:0x007f452b1ad390>:0x007f4528dec578>):
    28:   <% end %>
    29:   <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    30:     <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
    31:     <% query.inline_columns.each do |column| %>
    32:     <%= content_tag('td', column_content(column, issue), :class => column.css_classes) %>
    33:     <% end %>
    34:   </tr>
  plugins/redmine_wktime/lib/queries_helper_patch.rb:24:in `column_value'
  app/helpers/queries_helper.rb:135:in `column_content'
  plugins/redmine_category_tree/lib/redmine_category_tree/patches/queries_helper_patch.rb:23:in `column_content_with_issue_categories'
  plugins/redmine_tags/lib/redmine_tags/patches/queries_helper_patch.rb:23:in `column_content_with_redmine_tags'
```
 It's OK with v3.0.1

My Redmine version is : 3.3.5

**Comment by dhanasingh** [comment]
that is interesting, both erpmine 3.0.1 and 3.1 are compatible with redmine 3.4.2
erpmine 2.9 is compatible with Redmine 3.3
Can you please get the right versions and see if it solves the issue

**Comment by sruttloff** [comment]
I get the same error with Redmine 3.3.2 and Plugin Version 3.1
Would be nice if this problem could be solved soon.

**Comment by dhanasingh** [comment]
ERPmine 3.1 is not compatible with Redmine 3.3.x, you will have to get ERPmine 2.9 or upgrade Redmine 3.4.x

**Comment by sruttloff** [comment]
You are right.
Please close this issue.
