### ISSUE TITLE
Error 500 RuntimeError

### ISSUE THREAD

**Issue by cvxvp** [dhanasingh/redmine_wktime#161]
```
Started POST "/time_entries.json" for 185.70.13.135 at 2018-12-11 15:19:20 -0500
Processing by TimelogController#create as JSON
  Parameters: {"time_entry"=>{"hours"=>"0.02", "comments"=>"123", "issue_id"=>76, "activity_id"=>17}}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 32ms (ActiveRecord: 5.4ms)

RuntimeError (The timesheet for this period is locked, you cannot log time.):
  plugins/redmine_wktime/init.rb:837:in `controller_timelog_edit_before_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  plugins/redmine_wktime/lib/timelogcontroller_patch.rb:116:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
Can you help me solve this problem?

**Comment by dhanasingh** [comment]
it says the time sheet is locked, can you please check if the time sheet is locked, on the timesheet page, there should be a link for lock and it should have a date, anything prior to that period would be locked, please check.

**Comment by cvxvp** [comment]
Yes, my time sheet is locked, how unlock time sheet?
