### ISSUE TITLE
Redmine 4 - Upermitted Parameters

### ISSUE THREAD

**Issue by cfis** [dhanasingh/redmine_wktime#164]
Redmine 4.  Going to /wktime/index action:

```
ActionView::Template::Error (unable to convert unpermitted parameters to hash):
    1: <%= stylesheet_link_tag 'wk-time', :plugin => "redmine_wktime" %>
    2: <%= form_tag({}) do -%>
    3: <%= hidden_field_tag 'back_url', url_for(params) %>
    4: <div class="autoscroll">
    5: <table class="list time-entries">

plugins/redmine_wktime/app/views/wktime/_list.html.erb:2:in `block in _plugins_redmine_wktime_app_views_wktime__list_html_erb___1048891466109657099_50213600'
plugins/redmine_wktime/app/views/wktime/_list.html.erb:2:in `_plugins_redmine_wktime_app_views_wktime__list_html_erb___1048891466109657099_50213600'
plugins/redmine_wktime/app/views/wktime/_te_index.html.erb:136:in `_plugins_redmine_wktime_app_views_wktime__te_index_html_erb__3743084268686000311_83602860'
plugins/redmine_wktime/app/views/wktime/index.html.erb:17:in `_plugins_redmine_wktime_app_views_wktime_index_html_erb__3405252983847519438_75155520'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:98:in `block (2 levels) in index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:96:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

And then wkattendance/index:

```
ActionView::Template::Error (unable to convert unpermitted parameters to hash):
    3: <script>
    4: runperiodUrl="<%= "#{url_for(:controller => controller_name, :action => 'runPeriodEndProcess', :tab => controller.controller_name)}" %>";
    5: </script>
    6: <%= form_tag({}) do -%>
    7: <%= hidden_field_tag 'back_url', url_for(params) %>
    8: <% wktime_helper = Object.new.extend(WktimeHelper) %>
    9: <% if (wktime_helper.isAccountUser) %>

plugins/redmine_wktime/app/views/wkattendance/_list.html.erb:6:in `block in _plugins_redmine_wktime_app_views_wkattendance__list_html_erb__2183987571946467347_53817180'

```

Similar for /wkpayroll/index?tab=payroll, /wkattendance/clockindex?tab=clock, /wkpayroll/usrsettingsindex?tab=usersettings

**Comment by arunkumart1995** [comment]
Fix committed on Dev environment.

**Comment by cfis** [comment]
Thanks!

**Comment by dhanasingh** [comment]
erpmine 3.4 is compatible with Redmine 4.0
