### ISSUE TITLE
Migration error: NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x1d84aa8>

### ISSUE THREAD

**Issue by alexandrejobin** [dhanasingh/redmine_wktime#172]
Hi,

We try to install redmine_wktime v3.4 downloaded from your website. When we execute the migration statement `rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production`, we have this error: 

```
Migrating redmine_wktime (ERPmine)...
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x418a580>
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/plugins/redmine_wktime/db/migrate/001_create_wktimes.rb:1:in `<top (required)>'
D:in `disable_ddl_transaction'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/redmine/plugin.rb:481:in `migrate_plugin'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/redmine/plugin.rb:453:in `migrate'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/redmine/plugin.rb:464:in `migrate'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x418a580>
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/plugins/redmine_wktime/db/migrate/001_create_wktimes.rb:1:in `<top (required)>'
D:in `disable_ddl_transaction'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/redmine/plugin.rb:481:in `migrate_plugin'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/redmine/plugin.rb:453:in `migrate'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/redmine/plugin.rb:464:in `migrate'
D:/Bitnami/redmine-3.4.6-0/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

```
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  easy_gantt                     1.11
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redmine_agile                  1.4.6
  redmine_checklists             3.1.11
  redmine_favorite_projects      2.0.3
```

**Comment by dhanasingh** [comment]
ERPmine 3.4 is compatible with Redmine 4.0
For Redmine 3.4.6 please try ERPmine 3.3.4

**Comment by alexandrejobin** [comment]
It work. Thank you very much!
