### ISSUE TITLE
Error create tables

### ISSUE THREAD

**Issue by vsc55** [dhanasingh/redmine_wktime#195]
Redmine 4.0, update SVN revision 19439

Code error:
```
 # rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
== 1 CreateWktimes: migrating =================================================
-- create_table(:wktimes, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.7403s
-- add_index(:wktimes, :user_id)
   -> 0.5340s
-- add_index(:wktimes, :begin_date)
   -> 0.4412s
== 1 CreateWktimes: migrated (1.7160s) ========================================

== 2 CreateWkExpenseEntries: migrating ========================================
-- create_table(:wk_expense_entries, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.5327s
-- add_index(:wk_expense_entries, [:project_id], {:name=>:wk_expense_entries_project_id})
   -> 0.3671s
-- add_index(:wk_expense_entries, [:issue_id], {:name=>:wk_expense_entries_issue_id})
   -> 0.3999s
-- create_table(:wkexpenses, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.5324s
-- add_index(:wkexpenses, :user_id)
   -> 0.4421s
-- add_index(:wkexpenses, :begin_date)
   -> 0.3834s
== 2 CreateWkExpenseEntries: migrated (2.6583s) ===============================

== 3 CreateWkAttendances: migrating ===========================================
-- create_table(:wk_attendances, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.6076s
-- add_index(:wk_attendances, :user_id)
   -> 0.3754s
-- create_table(:wk_user_leaves, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.4491s
-- add_index(:wk_user_leaves, :user_id)
   -> 0.4421s
== 3 CreateWkAttendances: migrated (1.8747s) ==================================

== 4 CreateWkSalaryComponents: migrating ======================================
-- create_table(:wk_salary_components, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 1.6423s
-- create_table(:wk_user_salary_components, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.5748s
-- add_index(:wk_user_salary_components, :user_id)
   -> 0.6338s
-- add_index(:wk_user_salary_components, :salary_component_id)
   -> 0.4748s
-- create_table(:wk_salaries, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 1.7404s
-- add_index(:wk_salaries, :user_id)
   -> 0.4505s
-- add_index(:wk_salaries, :salary_component_id)
   -> 0.6415s
-- add_index(:wk_salaries, :salary_date)
   -> 0.5081s
-- create_table(:wk_h_user_salary_components, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.5659s
== 4 CreateWkSalaryComponents: migrated (7.2331s) =============================

== 5 CreateWkBilling: migrating ===============================================
-- create_table(:wk_addresses, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.9994s
-- create_table(:wk_accounts, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.6158s
-- create_table(:wk_account_projects, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.8254s
-- create_table(:wk_contracts, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 1.0740s
-- create_table(:wk_taxes, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.7914s
-- create_table(:wk_acc_project_taxes, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.5909s
-- create_table(:wk_invoices, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.7836s
-- create_table(:wk_invoice_items, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.7247s
-- create_table(:wk_billing_schedules, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.7747s
-- add_index(:wk_accounts, :address_id)
   -> 0.4090s
-- add_index(:wk_account_projects, :project_id)
   -> 0.5831s
-- add_index(:wk_account_projects, :account_id)
   -> 0.3498s
-- add_index(:wk_contracts, :project_id)
   -> 0.7416s
-- add_index(:wk_contracts, :account_id)
   -> 0.3497s
-- add_index(:wk_acc_project_taxes, :account_project_id)
   -> 0.3499s
-- add_index(:wk_acc_project_taxes, :tax_id)
   -> 0.8163s
-- add_index(:wk_invoices, :account_id)
   -> 0.3416s
-- add_index(:wk_invoices, :invoice_number, {:unique=>true})
   -> 0.5759s
-- add_index(:wk_invoice_items, :invoice_id)
   -> 0.4071s
-- add_index(:wk_invoice_items, :project_id)
   -> 0.3333s
-- add_index(:wk_billing_schedules, :account_project_id)
   -> 0.7000s
-- add_index(:wk_billing_schedules, :invoice_id)
   -> 0.3579s
== 5 CreateWkBilling: migrated (13.4979s) =====================================

== 6 CreateWkAccounting: migrating ============================================
-- create_table(:wk_ledgers, {:options=>"ENGINE=InnoDB", :id=>:integer})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'wk_ledgers' already exists: CREATE TABLE `wk_ledgers` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `opening_balance` decimal(16,2), `currency` varchar(5), `ledger_type` varchar(3) NOT NULL, `owner` varchar(1) DEFAULT 's' NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:871:in `block in method_missing'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `say_with_time'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:860:in `method_missing'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:32:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:73:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:141:in `create_table'
/opt/redmine/redmine-4.0/plugins/redmine_wktime/db/migrate/006_create_wk_accounting.rb:10:in `change'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:814:in `exec_migration'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:796:in `migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:977:in `migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1345:in `ddl_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:504:in `up'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:488:in `migrate'
/opt/redmine/redmine-4.0/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'wk_ledgers' already exists: CREATE TABLE `wk_ledgers` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `opening_balance` decimal(16,2), `currency` varchar(5), `ledger_type` varchar(3) NOT NULL, `owner` varchar(1) DEFAULT 's' NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:871:in `block in method_missing'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `say_with_time'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:860:in `method_missing'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:32:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:73:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:141:in `create_table'
/opt/redmine/redmine-4.0/plugins/redmine_wktime/db/migrate/006_create_wk_accounting.rb:10:in `change'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:814:in `exec_migration'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:796:in `migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:977:in `migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1345:in `ddl_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:504:in `up'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:488:in `migrate'
/opt/redmine/redmine-4.0/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

Caused by:
Mysql2::Error: Table 'wk_ledgers' already exists
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/lib64/ruby/gems/2.4.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:871:in `block in method_missing'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `say_with_time'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:860:in `method_missing'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:32:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:73:in `create_table'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:141:in `create_table'
/opt/redmine/redmine-4.0/plugins/redmine_wktime/db/migrate/006_create_wk_accounting.rb:10:in `change'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:814:in `exec_migration'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:796:in `migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:977:in `migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1345:in `ddl_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:504:in `up'
/usr/local/lib64/ruby/gems/2.4.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:488:in `migrate'
/opt/redmine/redmine-4.0/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by vsc55** [comment]
I have uninstalled the plugin I have checked that all the tables have been deleted and when vover to install it has worked.

**Comment by dhanasingh** [comment]
Glad it worked fine
