### ISSUE TITLE
NameError: uninitialized constant IssuesControllerPatch

### ISSUE THREAD

**Issue by vsc55** [dhanasingh/redmine_wktime#265]
Redmine_wktime: 4.5.2
Redmine 4.2.5.stable.21531

Update show error:
```bash
#  rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
rake aborted!
NameError: uninitialized constant IssuesControllerPatch
/opt/redmine/redmine-4.2-stable/plugins/redmine_wktime/init.rb:288:in `<top (required)>'
/opt/redmine/redmine-4.2-stable/lib/redmine/plugin.rb:187:in `block in load'
/opt/redmine/redmine-4.2-stable/lib/redmine/plugin.rb:178:in `each'
/opt/redmine/redmine-4.2-stable/lib/redmine/plugin.rb:178:in `load'
/opt/redmine/redmine-4.2-stable/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/redmine/redmine-4.2-stable/config/environment.rb:16:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Trace:
```bash
#  rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant IssuesControllerPatch
/opt/redmine/redmine-4.2-stable/plugins/redmine_wktime/init.rb:288:in `<top (required)>'
/opt/redmine/redmine-4.2-stable/lib/redmine/plugin.rb:187:in `block in load'
/opt/redmine/redmine-4.2-stable/lib/redmine/plugin.rb:178:in `each'
/opt/redmine/redmine-4.2-stable/lib/redmine/plugin.rb:178:in `load'
/opt/redmine/redmine-4.2-stable/config/initializers/30-redmine.rb:20:in `<top (required)>'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/engine.rb:663:in `block in load_config_initializer'
/usr/lib64/ruby/gems/2.5.0/gems/activesupport-5.2.7/lib/active_support/notifications.rb:170:in `instrument'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/engine.rb:662:in `load_config_initializer'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/engine.rb:619:in `each'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/initializable.rb:32:in `instance_exec'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/initializable.rb:32:in `run'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib64/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/lib64/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib64/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib64/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib64/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/initializable.rb:50:in `each'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/lib64/ruby/2.5.0/tsort.rb:415:in `call'
/usr/lib64/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib64/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib64/ruby/2.5.0/tsort.rb:347:in `each'
/usr/lib64/ruby/2.5.0/tsort.rb:347:in `call'
/usr/lib64/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib64/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/lib64/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/initializable.rb:60:in `run_initializers'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.2-stable/config/environment.rb:16:in `<top (required)>'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/application.rb:337:in `require'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/application.rb:337:in `require_environment!'
/usr/lib64/ruby/gems/2.5.0/gems/railties-5.2.7/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/lib64/ruby/gems/2.5.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by dhanasingh** [comment]
Erpmine 4.5.2 is compatible with Redmine 5.0
Please install Erpmine 4.5.1 for Redmine 4.2.x
Please check the compatibility here http://www.erpmine.org/projects/erpmine/wiki/Download

**Comment by vsc55** [comment]
Thanks @dhanasingh,
I have installed version 4.5.1 and now it works correctly.
