### ISSUE TITLE
redmine_wktime migration error - NameError: uninitialized constant IssuesControllerPatch

### ISSUE THREAD

**Issue by shreyarajwade** [dhanasingh/redmine_wktime#267]
I am using redmine v4.5.2 and encountered the following error while installing the plugin - 

```
rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
fatal: not a git repository (or any of the parent directories): .git
rake aborted!
NameError: uninitialized constant IssuesControllerPatch
/opt/bitnami/redmine/plugins/redmine_wktime/init.rb:288:in `<top (required)>'
/opt/bitnami/redmine/lib/redmine/plugin.rb:187:in `block in load'
/opt/bitnami/redmine/lib/redmine/plugin.rb:178:in `each'
/opt/bitnami/redmine/lib/redmine/plugin.rb:178:in `load'
/opt/bitnami/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/bitnami/redmine/config/environment.rb:16:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Has anyone encountered this error before?

**Comment by dhanasingh** [comment]
Are you trying to install erpmine 4.5.2 ? do you have redmine 5.0 ?
check the compatibility matrix here https://erpmine.org/projects/erpmine/wiki/Download?page=Download

**Comment by shreyarajwade** [comment]
I am using Redmine 4.2.5 and erpmine version 4.5.2. I checked the compatibility matrix. Downloaded the erpmine v4.5.1.
Thank you!
