### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by YetiSPb** [dhanasingh/redmine_wktime#276]
root@1123097-ca62001:/opt/redmine/plugins# su redmine
cd /opt/redmine
bundle install
redmine@1123097-ca62001:~/plugins$ rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
(in /opt/redmine)
rake aborted!
Gem::LoadError: You have already activated rake 13.0.3, but your Gemfile requires rake 13.0.6. Prepending `bundle exec` to your command may solve this.
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:308:in `check_for_activated_spec!'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:25:in `block in setup'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/spec_set.rb:155:in `each'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/spec_set.rb:155:in `each'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:24:in `map'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:24:in `setup'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler.rb:161:in `setup'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/setup.rb:10:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/ui/shell.rb:136:in `with_level'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/ui/shell.rb:88:in `silence'
/var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/setup.rb:10:in `<top (required)>'
/opt/redmine/config/boot.rb:6:in `<top (required)>'
/opt/redmine/config/application.rb:3:in `<top (required)>'
/opt/redmine/Rakefile:5:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by YetiSPb** [comment]
gem install rake
