### ISSUE TITLE
Error on install - Redmine 5.1.1 - WKtime 4.7.1

### ISSUE THREAD

**Issue by neofly** [dhanasingh/redmine_wktime#306]
Hi,
I wanted to try your plugin but when I try to install the plugin with : `RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_wktime` I have an error : **Tried to load unspecified class: Set**

Psych is not in the Gemfile of redmine 5.1.1 (but it was in the redmine 5.0 Gemfile)

Thanks for your help.

Here is the output  :
```
Caused by:
Psych::DisallowedClass: Tried to load unspecified class: Set
/opt/redmine/redmine5.1.1/app/models/setting.rb:111:in `value'
/opt/redmine/redmine5.1.1/app/models/setting.rb:125:in `[]'
/opt/redmine/redmine5.1.1/app/models/setting.rb:320:in `plugin_redmine_wktime'
/opt/redmine/redmine5.1.1/plugins/redmine_wktime/db/migrate/20210902125010_create_wk_delivery_items.rb:27:in `block (2 levels) in change'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:752:in `up'
/opt/redmine/redmine5.1.1/plugins/redmine_wktime/db/migrate/20210902125010_create_wk_delivery_items.rb:26:in `block in change'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:788:in `block in reversible'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1016:in `execute_block'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:788:in `reversible'
/opt/redmine/redmine5.1.1/plugins/redmine_wktime/db/migrate/20210902125010_create_wk_delivery_items.rb:25:in `change'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:867:in `exec_migration'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:850:in `block in migrate'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:849:in `migrate'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1037:in `migrate'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1382:in `ddl_transaction'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1302:in `each'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1251:in `block in migrate'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1251:in `migrate'
/opt/redmine/redmine5.1.1/lib/redmine/plugin.rb:470:in `up'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/migration.rb:1061:in `migrate'
/opt/redmine/redmine5.1.1/lib/redmine/plugin.rb:506:in `migrate_plugin'
/opt/redmine/redmine5.1.1/lib/redmine/plugin.rb:443:in `migrate'
/opt/redmine/redmine5.1.1/lib/redmine/plugin.rb:454:in `migrate'
/opt/redmine/redmine5.1.1/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/opt/redmine/redmine5.1.1/vendor/bundle/ruby/3.1.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-3.1.4/bin/ruby_executable_hooks:22:in `eval'
/opt/redmine/.rvm/gems/ruby-3.1.4/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by neofly** [comment]
I forgot to specify the migration concerned is : 20210902125010_create_wk_delivery_items.rb (but it's visible in the output I previously sent)

**Comment by cdhana17** [comment]
Hi,
what version of ruby, DB  and OS do you have ?

if you remove the plugin from the plugin folder, does the redmine work fine ?

Thanks 
Dhanalakshmi

**Comment by neofly** [comment]
Hello,
I use Ruby 3.1.4 with MariaDB 10.5 (Mysql2 adapter) on Debian 11.
Redmine was working fine without the plugin installed.

Thanks.
