### ISSUE TITLE
uninitialized constant WktimeHelper

### ISSUE THREAD

**Issue by noobchamp** [dhanasingh/redmine_wktime#53]
Hi, i cant install pluggin, this its my detail issue from production.log

ActionView::Template::Error (uninitialized constant WktimeHelper):
    22: <div id="top-menu">
    23:     <div id="account">
    24:         <%= render_menu :account_menu -%>
    25:     </div>
    26:     <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
    27:     <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
    28: </div>
  lib/redmine/menu_manager.rb:199:in `call'
  lib/redmine/menu_manager.rb:199:in`allowed_node?'
  lib/redmine/menu_manager.rb:166:in `block in menu_items_for'
  lib/redmine/menu_manager.rb:165:in`each'
  lib/redmine/menu_manager.rb:165:in `menu_items_for'
  lib/redmine/menu_manager.rb:90:in`render_menu'
  app/views/layouts/base.html.erb:25:in `_app_views_layouts_base_html_erb___1139484040708537044_51438460'

Thanks

**Comment by suganya-thulasiraman** [comment]
We couldn't reproduce this issue. We have tested it on Linux CentOS 6.6, MySQL 5.5.49, Redmine 3.2.1 and also in Windows 7 and 8, PostgreSQL 9.4. Could you please provide us your environment details.

And also could you please give us the list of other Plugins used with Redmine 3.2.1

**Comment by jayankaghosh** [comment]
Hey, I'm having the same error. I am running Redmine 3.2.1 on Nginx in Ubuntu. 

Here is the list of other plugins I am using 
     -Clipboard image paste
     -Progressive Projects List plugin
     -Redmine Agile plugin (Light version)
     -Redmine Checklists plugin (Light version)
     -Redmine People plugin (Light version)
     -ERPmine


Here is my production.log

ActionView::Template::Error (uninitialized constant WktimeHelper::Import):
    273: 		<p style="padding-left: 130px;">
    274: 		  <label><%= l(:setting_date_format) %></label>
    275: 		  <% wktime_helper = Object.new.extend(WktimeHelper) %>
    276: 		  <%= select_tag 'settings[wktime_field_datetime]', options_for_select(wktime_helper.date_format_options, :selected => @settings['wktime_field_datetime'].blank? ? 0 : @settings['wktime_field_datetime'] ) %>
    277: 		</p>	
    278: 		<table>
    279: 		<thead>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___1899163224435523439_70026162944120'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___1899163224435523439_70026162944120'
  app/helpers/application_helper.rb:321:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___4346190205523225087_70026163009500'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___4346190205523225087_70026163009500'

**Comment by dhanasingh** [comment]
This looks like a version comparability issue, what version of ERPmine are you using ?

**Comment by jayankaghosh** [comment]
Yes the version conflict was the issue. I installed Erpmine 1.9 and it worked, I'll upgrade my redmine when I get time. Thank you so much for the quick and precise reply

**Comment by rubywarlock** [comment]
Some error.

Environment:
  Redmine version                3.2.3.stable.14369
  Ruby version                   2.3.1
  Rails version                  4.2
  Environment                    development
  Database adapter               Mysql2

**Comment by dhanasingh** [comment]
what version of erpmine are you using ?

**Comment by rubywarlock** [comment]
> what version of erpmine are you using ?

2.2

**Comment by dhanasingh** [comment]
Can you send us the error from the log file ?
