### ISSUE TITLE
Undefined method `each_with_index' for nil:NilClass

### ISSUE THREAD

**Issue by garethflowers** [dhanasingh/redmine_wktime#67]
We are randomly getting an `Undefined method 'each_with_index' for nil:NilClass` error when trying to post work times:

```
Started POST "/wktime/update" for 172.16.68.60 at 2016-09-29 12:13:36 +0000
Processing by WktimeController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"lP8UNXcs3DdiLaWxG7T0GrJT8qeSRhghHZRBe0t7lzUm4pvdCzlc1l8KW0axTwOO+qz4A4SdTKh4Bu8DDJSpyg==", "tab"=>"wktime", "back_url"=>"http://XXXX/wktime/index", "getissues_url"=>"/wktime/getissues", "getactivities_url"=>"/wktime/getactivities", "deleterow_url"=>"/wktime/deleterow", "user_id"=>"8", "startday"=>"2016-09-26", "select_issues_tracker"=>["0"], "time_entry"=>[{"project_id"=>"36", "issue_id"=>"", "activity_id"=>"9", "comments"=>""}, {"project_id"=>"1", "issue_id"=>"", "activity_id"=>"9", "comments"=>""}], "hours-2"=>["", "", "", "", "", "", ""], "ids-2"=>["", "", "", "", "", "", ""], "disabled-2"=>["false", "false", "false", "false", "false", "false", "false"], "hours1"=>[".5", "", "", "", "", "", ""], "ids1"=>["", "", "", "", "", "", ""], "disabled1"=>["false", "false", "false", "false", "false", "false", "false"], "total"=>"0", "unit"=>"", "hidden_clock_in_out"=>"", "wktime_save_continue"=>"Save and continue"}
  Current user: XXXX (id=8)
Completed 500 Internal Server Error in 77ms (ActiveRecord: 20.3ms)

NoMethodError (undefined method `each_with_index' for nil:NilClass):
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1149:in `block in gatherEntries'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1134:in `each'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1134:in `each_with_index'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1134:in `gatherEntries'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:153:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by danpfe** [comment]
@garethflowers Did you ever find a solution to this problem? Having exactly the same issue (latest wktime, latest redmine)

**Comment by dhanasingh** [comment]
can you give some details on OS, database, Ruby and Rails, Browser versions ?
