### ISSUE TITLE
Error: uninitialized constant WkreportController during migration wktimes

### ISSUE THREAD

**Issue by peishar** [dhanasingh/redmine_wktime#70]
Hello,
When attempting to migrate the plugin wktime v2.3 of redmine v2.3.6 to v3.3, we get the following error:
```
rake aborted!
NameError: uninitialized constant WkreportController
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_wktime-2.3/init.rb:264:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:411:in `call'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```
Thanks

**Comment by karthickmadhiazhagan** [comment]
Could you Migrate Redmine to v3.3 first and then migrate T&A plugin.

**Comment by peishar** [comment]
Thanks karthickmadhiazhagan, 

I did it like that

Regards

**Comment by karthickmadhiazhagan** [comment]
Are you using a fresh release of wk_time or upgrading older version of wk_time?
If you are using fresh release then make Redmine 3.3 to work then install wk_time.

**Comment by peishar** [comment]
I disabled the line .../redmine_wktime-2.3/init.rb

`#WkreportController.send(:include, WkreportControllerPatch)`

Migrating is right, but when you start the server.

Completed 500 Internal Server Error in 434ms (ActiveRecord: 4.5ms)

```
ActionView::Template::Error (Missing partial wktime/_attendance_widget with {:locale=>[:es, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "/opt/bitnami/apps/redmine/htdocs/plugins/redmine_work_time/app/views"
  * "/opt/bitnami/apps/redmine/htdocs/plugins/redmine_wiki_extensions/app/views"
  * "/opt/bitnami/apps/redmine/htdocs/plugins/redmine_theme_changer/app/views"
  * "/opt/bitnami/apps/redmine/htdocs/plugins/redmine_knowledgebase/app/views"
  * "/opt/bitnami/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
  * "/opt/bitnami/apps/redmine/htdocs/app/views"
):
    104:         <%= view_layouts_base_sidebar_hook_response %>
    105:     </div>
    106: 
    107:     <div id="content">
    108:         <%= render_flash_messages %>
    109:         <%= yield %>
    110:         <%= call_hook :view_layouts_base_content %>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:107:in `_app_views_layouts_base_html_erb__4379746037070471377_70059590393380'
  app/controllers/application_controller.rb:488:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:486:in `render_error'
  app/controllers/application_controller.rb:474:in `render_404'
  app/controllers/application_controller.rb:498:in `missing_template'
```
:(

**Comment by peishar** [comment]
Resolved. Plugin folder can not have version numbers.

Thanks
