### ISSUE TITLE
Install aborted : "NameError: uninitialized constant WkreportController"

### ISSUE THREAD

**Issue by davidbouche** [dhanasingh/redmine_wktime#75]
Hello,

I've failed to install your Time & Attendance plugin.

Here's the error message : 

```
$ rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
rake aborted!
NameError: uninitialized constant WkreportController
/home/david/public_html/redmine.waisso/plugins/redmine_wktime-2.4/init.rb:325:in `<top (required)>'
/home/david/public_html/redmine.waisso/lib/redmine/plugin.rb:155:in `block in load'
/home/david/public_html/redmine.waisso/lib/redmine/plugin.rb:146:in `each'
/home/david/public_html/redmine.waisso/lib/redmine/plugin.rb:146:in `load'
/home/david/public_html/redmine.waisso/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/david/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/home/david/public_html/redmine.waisso/config/environment.rb:14:in `<top (required)>'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/home/david/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/david/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/david/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/david/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Information about my environnement : 

```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ bundle --version
Bundler version 1.13.5
$ head doc/CHANGELOG 
== Redmine changelog

Redmine - project management software
Copyright (C) 2006-2016  Jean-Philippe Lang
http://www.redmine.org/

== 2016-10-10 v3.3.1
```

Does your plugin is compatible with the last Redmine version ? (3.3.1)

Thanks for your support,
David

**Comment by karthickmadhiazhagan** [comment]
Hi,
 Looking at the stack trace the plugin folder name is "redmine_wktime-2.4".
Plugin folder name should be "redmine_wktime". Please remove "2.4"  from the folder name and try again. 

Thanks,
Karthick
