### ISSUE TITLE
Time and Expenses filters are not updated

### ISSUE THREAD

**Issue by hooger** [dhanasingh/redmine_wktime#79]
Hello,

I'm trying to install and use ERPmine plugin 2.5.2 however I have a problem. When I go to ERPmine, and under Time tab, choose a Project, the Member filters does not update accordingly to the Project. If I click on any name, communication with the server starts (grey bar on the bottom of the browser says ''waiting for hostname...'') and the Members are updated. If I choose someone who is not part of the Project, Member jumps to All Users.

If I switch to a group it goes to internal error, even if the chosen member is part of given group. Redmine production log says:

```
Started GET "/wktime/index?utf8=%E2%9C%93&tab=wktime&searchlist=wktime&project_id=12&filter_type=2&user_id=22&status%5B%5D=e&status%5B%5D=n&status%5B%5D=r&status%5B%5D=s&status%5B%5D=a&period_type=1&period=current_month" for 94.21.221.118 at 2016-12-03 12:17:32 +0100
Processing by WktimeController#index as HTML
  Parameters: {"utf8"=>"<E2><9C><93>", "tab"=>"wktime", "searchlist"=>"wktime", "project_id"=>"12", "filter_type"=>"2", "user_id"=>"22", "status"=>["e", "n", "r", "s", "a"], "period_type"=>"1", "period"=>"current_month"}
  Current user: horvathg (id=3)
Completed 500 Internal Server Error in 30ms (ActiveRecord: 9.5ms)
NoMethodError (undefined method `all' for nil:NilClass):
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1074:in `getGrpMembers'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1569:in `setMembers'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:47:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode' 
```

```
Environment:
  Redmine version                3.2.3.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Filesystem                     
Redmine plugins:
  event_notifications            3.2.1
  mega_calendar                  1.4.0
  progressive_projects_list      2.0.1
  redmine_agile                  1.4.1
  redmine_checklists             3.1.5
  redmine_contacts               4.0.4
  redmine_contacts_invoices      4.1.1
  redmine_finance                2.1.1
  redmine_people                 1.2.0
  redmine_wktime                 2.5.2
  redmine_zenedit                0.0.2
```

Any idea what can be the problem?
Thanks in advance!
hooger

**Comment by dhanasingh** [comment]
It could be a compatibility issue.
ERPmine 2.5.2 is compatible with Redmine 3.3
ERPmine 2.2 is compatible with Redmine 3.2

Can you try the right version and see if it works for you ?
