### ISSUE TITLE
Edit role/id/edit issue 

### ISSUE THREAD

**Issue by peterdu88** [dhanasingh/redmine_wktime#80]
Showing
redmine-3.3.1-0/apps/
app/views/roles/_form.html.erb where line #87 raised:
undefined method `accessor' for #<ActiveRecord::Type::Value:0x50d49b0>
Trace of template inclusion: app/views/roles/edit.html.erb
Rails.root: 

app/models/role.rb:213:in `permissions_all_trackers'
app/models/role.rb:222:in `permissions_all_trackers?'
app/views/roles/_form.html.erb:87:in `block in _app_views_roles__form_html_erb__612902754_41285976'
app/views/roles/_form.html.erb:82:in `each'
app/views/roles/_form.html.erb:82:in `_app_views_roles__form_html_erb__612902754_41285976'
app/views/roles/edit.html.erb:4:in `block in _app_views_roles_edit_html_erb__949090999_42134160'
app/helpers/application_helper.rb:1051:in `labelled_form_for'
app/views/roles/edit.html.erb:3:in `_app_views_roles_edit_html_erb__949090999_42134160'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by peterdu88** [comment]
that is different version, need to migrate the databases.
