### ISSUE TITLE
Compatibiliy with projects_tree_view

### ISSUE THREAD

**Issue by demahom27** [dhanasingh/redmine_wktime#86]
The plugins projects_tree_view is for the display format of the project in a tree format. 
After installing the wktime plugin, whenever i try to access to the 'Projects' page i get an error with the following log : 

```
Started GET "/projects"
Processing by ProjectsController#index as HTML
  Current user: admin (id=1)
  Rendered plugins/projects_tree_view/app/views/projects/index.html.erb within layouts/base (126.8ms)
Completed 500 Internal Server Error in 143ms (ActiveRecord: 4.6ms)

ActionView::Template::Error (undefined method `favorite_project_modules_links' for #<#<Class:0x00000004b83018>:0x007fd8a4352990>):
    45:           <%= project.active? ? link_to_project(project) : h(project.name) %>
    46:           <span class="empty <%= "my-project" if User.current.member_of?(project) %>">&nbsp;</span></td>
    47:         <td><%= textilizable project.short_description.gsub(/\!.+\!/,""), :project => project %></td>
    48:         <td><%= favorite_project_modules_links(project) %></td>
    49:         <% if show_project_progress %>
    50:           <td><%= render_project_progress(project) %></td>
    51:         <% end %>
  plugins/projects_tree_view/app/views/projects/index.html.erb:48:in `block in _plugins_projects_tree_view_app_views_projects_index_html_erb___2740585350986866952_39792160'
  app/models/project.rb:796:in `block in project_tree'
  app/models/project.rb:792:in `each'
  app/models/project.rb:792:in `project_tree'
  app/helpers/application_helper.rb:375:in `project_tree'
  plugins/projects_tree_view/app/views/projects/index.html.erb:36:in `_plugins_projects_tree_view_app_views_projects_index_html_erb___2740585350986866952_39792160'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode
```

**Comment by dhanasingh** [comment]
What version of wktime and Redmine are you using ?

**Comment by demahom27** [comment]
Redmine : 3.3.0.stable 
Wktime: 2.6

**Comment by karthickmadhiazhagan** [comment]
If you uninstall ERPmine, Is the project_tree working fine?

**Comment by demahom27** [comment]
Yes
